services:

    tianos.listener.doctrine.settings:
        class: Bundle\SettingsBundle\EventListener\DoctrineListenerService
        arguments: ["@security.token_storage"]
        tags:
          - { name: doctrine.event_listener, event: postUpdate }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: postLoad }
          - { name: doctrine.event_listener, event: postRemove }

    tianos.api.controller.settings:
        class: Bundle\SettingsBundle\Controller\ApiController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.api.controller.settings, alias: tianos.api.controller.settings }

    tianos.backend.controller.settings:
        class: Bundle\SettingsBundle\Controller\BackendController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.controller.settings, alias: tianos.backend.controller.settings }

    tianos.frontend.controller.settings:
        class: Bundle\SettingsBundle\Controller\FrontendController
        arguments: [ Bundle\GridBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.frontend.controller.settings, alias: tianos.frontend.controller.settings }

    tianos.repository.settings:
        class: Dummy
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Bundle\SettingsBundle\Entity\Settings ]

    tianos.type.settings:
        class: Bundle\SettingsBundle\Form\Type\SettingsType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: tianos.type.settings }