backend_user_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.user:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            roles_granted:
                - ROLE_USER_VIEW
            vars:
                subheader: sylius.ui.manage_your_user_catalog
                icon: cube
                body_css: grid-body-css
                copy_clipboard: true
                files_upload:
                    class_name: User
                    file_type: images
                    filter: file_thumb_500_417
                    route:
                        create: backend_files_create
                        open_modal: backend_files_open_modal
            grid:
                icon: user
                box_class: primary
                title: Gestionar usuarios
                modal:
                    create:
                        title: Crear usuario
                        size: modal-lg
                    edit:
                        title: Editar usuario
                        size: modal-lg
                    view:
                        title: Ver usuario
                        size: modal-lg
                    change_password:
                        title: Cambiar password
                data_table:
                    route:
                        info: backend_user_info
                        view: backend_user_view
                        edit: backend_user_edit
                        create: backend_user_create
                        delete: backend_user_delete
                        view_profile: backend_user_profile
                        change_password: backend_user_change_password
                    table_button:
                        #- edit
                        #- delete
                        #- view_profile
                        #- change_password
                    table_button_header:
                        - create
                        - info
                    table_option:
                        pageLength: 50
                        dom: "'<\"top\"iflp><\"clear\">rt<\"bottom\"iflp>'"
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: data-slug
                          value: aData.slug
                        - key: class
                          value: "'alert'"
                    columns:
                        - obj: " '<span class=\"badge bg-light-blue-active\">' + obj.id + '</span>' "
                          defs:
                              targets: 0
                              searchable: 1
                              sorting: 1
                              orderable: 1
                              type: num
                              width: 4%
                              title: '#'
                              className: modal-view text-center
                        - obj: obj.files
                          options:
                              property: " return (obj.files[0] != null) ? '<img src=\"' + obj.files[0] + '\" class=\"img-circle img-thumbnail\">' : '<i class=\"fa fa-2x fa-fw fa-image \"></i>' "
                          defs:
                              targets: 1
                              title: Thumb
                              width: 5.5%
                              sorting: 0
                              orderable: 0
                              className: image-upload text-center
                        - obj: obj.name_box
                          defs:
                              targets: 2
                              orderable: 1
                              sorting: 1
                              title: Nombre
                              className: modal-edit
                              filter: 1
                        - obj: obj.email
                          defs:
                              targets: 3
                              title: '<i class="fa fa-fw fa-envelope-o"></i> Email'
                              filter: 1
                        - obj: " '<span class=\"badge bg-green\">' + obj.username + '</span>' "
                          defs:
                              targets: 4
                              title: '<i class="fa fa-fw fa-feed"></i> Username'
                              className: text-center
                              filter: 1
                        - obj: obj.profile.name
                          options:
                              icon: imagen
                              property: " return (obj.profile.slug == 'client') ? '<span class=\"badge bg-navy\">' + obj.profile.name + '</span>' : '<span class=\"badge bg-purple\">' + obj.profile.name + '</span>' "
                          defs:
                              targets: 5
                              title: '<i class="fa fa-fw fa-user"></i> Profile'
                              className: text-center
                              filter: 1
                        - obj: obj.created_at
                          defs:
                              targets: 6
                              title: '<i class="fa fa-fw fa-calendar"></i> Creado'
                              className: text-center
                        - obj: " '<button class=\"btn btn-xs bg-olive\"><i class=\"fa fa-fw fa-user\"></i></button>' "
                          defs:
                              targets: 7
                              title: Perfil
                              width: 4%
                              sorting: 0
                              orderable: 0
                              className: profile-button-id text-center
                        - obj: " '<button class=\"btn btn-xs btn-info\"><i class=\"fa fa-fw fa-lock\"></i></button>' "
                          defs:
                              targets: 8
                              title: Password
                              width: 4%
                              sorting: 0
                              orderable: 0
                              className: change-password-id text-center
                        - obj: " '<button class=\"btn btn-xs btn-danger\"><i class=\"fa fa-fw fa-trash\"></i></button>' "
                          defs:
                              targets: 9
                              title: Eliminar
                              width: 4%
                              sorting: 0
                              orderable: 0
                              className: modal-delete text-center
            form:
                type: Bundle\UserBundle\Form\Type\UserType
            repository:
                service: tianos.repository.user
                method: findAll
                arguments: [$userId]
                vars:
                    serialize_group_name: crud

backend_user_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.user:createAction
        _tianos:
            action: create
            template: UserBundle:Backend/Form:form.html.twig
            entity: Bundle\UserBundle\Entity\User
            roles_granted:
                - ROLE_USER_CREATE
            form:
                type: Bundle\UserBundle\Form\Type\UserType
            repository:
                vars:
                    serialize_group_name: crud

backend_user_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.user:editAction
        _tianos:
            action: edit
            template: UserBundle:Backend/Form:form.html.twig
            roles_granted:
                - ROLE_USER_EDIT
            form:
                type: Bundle\UserBundle\Form\Type\UserType
            repository:
                service: tianos.repository.user
                method: find
                arguments: [$userId]
                vars:
                    serialize_group_name: crud

backend_user_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.user:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            roles_granted:
                - ROLE_USER_DELETE
            repository:
                service: tianos.repository.user
                method: find
                arguments: [$userId]
            vars:
#                body_css: grid-body-css

backend_user_change_password:
    path: /change-password
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.user:changePasswordAction
        _tianos:
            action: edit
            template: UserBundle:Backend/Form:change_password.html.twig
            entity: Bundle\UserBundle\Entity\ChangePassword2
            form:
                type: Bundle\UserBundle\Form\Type\UserChangePasswordType2
            repository:
                service: tianos.repository.user
                method: find
                arguments: [$userId]
                vars:
                    serialize_group_name: crud

backend_user_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.user:viewAction
        _tianos:
            action: view
            template: UserBundle:Backend/Informative:view.html.twig
            roles_granted:
                - ROLE_USER_VIEW
            repository:
                service: tianos.repository.user
                method: find
                arguments: [$userId]
                vars:
                    serialize_group_name: crud

backend_user_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.user:infoAction
        _tianos:
            action: info
            template: UserBundle:Backend/Informative:info.html.twig

backend_user_profile:
    path: /{slug}
    methods: [GET]
    defaults:
        slug: null
        _controller: tianos.backend.controller.user:profileAction
        _tianos:
            action: edit
            template: UserBundle:Backend/Profile:index.html.twig
            vars:
                body_css: tianos-profile-user
                button_add_friend: add-friend
                button_remove_friend: remove-friend
            form:
                type: Bundle\GoogleBundle\Form\Type\GoogleType
            repository:
                service: tianos.repository.user
                method: findOneBySlug
                arguments: [$userId]
                vars:
                    serialize_group_name: user