backend_security_super_login_check:
    path: /login_check

backend_security_super_logout:
    path: /logout

backend_security_super_login:
    path: /login
    methods: [GET, POST]
    defaults:
        _controller: tianos.security.controller.user:loginAction
        _tianos:
            action: create
            template: UserBundle:BackendSuper/Security:login.html.twig
