backend_ticket_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.ticket:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            vars:
                subheader: sylius.ui.manage_your_ticket_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
            grid:
                icon: ticket
                box_class: primary
                title: Gestionar ticket
                data_table:
                    route:
                        info: backend_ticket_info
                        view: backend_ticket_view
                        create: backend_ticket_create_internal
                        ticket_edit: backend_ticket_edit
#                        edit: backend_ticket_edit
#                        delete: backend_ticket_delete
                    table_button:
                        - ticket_edit
#                        - edit
#                        - delete
                    table_button_header:
#                        - create
                        - info
                    table_option:
                        pageLength: 10
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: '#'
                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
                        - name: Nombre servicio
                          obj: obj.name
                        - name: Cliente
                          obj: obj.client.name + ' ' + obj.client.last_name
#                        - name: Total price
#                          obj: obj.total_price
#                          options:
#                              icon: money
                        - name: Creado
                          obj: obj.created_at
                          options:
                              icon: calendar
            form:
                type: Bundle\TicketBundle\Form\Type\TicketType
            repository:
                service: tianos.repository.ticket
                method: findAll
                arguments: [$ticketId]
                vars:
                    serialize_group_name: crud

backend_ticket_create_internal:
    path: /create-internal
    methods: [GET, POST]
    defaults:
        _controller: tianos.backend.controller.ticket:createInternalAction
        _tianos:
            action: create
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            tree:
                icon: file-text-o
                box_class: primary
                title: Gestionar servicios
                main_div: box-main-div
                main_ul: box-main-ul
                child_ul: box-child-ul
                li_span: li-span
            entity: Bundle\TicketBundle\Entity\Ticket
            template: TicketBundle:BackendTicket/Grid:create_internal.html.twig
            form:
                type: Bundle\TicketBundle\Form\Type\TicketType
            repository:
                vars:
                    serialize_group_name: crud

backend_ticket_create_external:
    path: /create-external
    methods: [GET, POST]
    defaults:
        _controller: tianos.backend.controller.ticket:createExternalAction
        _tianos:
            action: create
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            tree:
                icon: file-text-o
                box_class: primary
                title: Gestionar servicios
                main_div: box-main-div
                main_ul: box-main-ul
                child_ul: box-child-ul
                li_span: li-span
            entity: Bundle\TicketBundle\Entity\Ticket
            template: TicketBundle:BackendTicket/Grid:create_external.html.twig
            form:
                type: Bundle\TicketBundle\Form\Type\TicketType
            repository:
                vars:
                    serialize_group_name: crud

backend_ticket_edit:
    path: /edit/{id}
    methods: [GET, POST]
    defaults:
        id: null
        _controller: tianos.backend.controller.ticket:editAction
        _tianos:
            action: edit
            vars:
               body_css: grid-body-css
               serialize_group_name: crud
            tree:
               icon: file-text-o
               box_class: primary
               title: Gestionar servicios
               main_div: box-main-div
               main_ul: box-main-ul
               child_ul: box-child-ul
               li_span: li-span
            entity: Bundle\TicketBundle\Entity\Ticket
            template: TicketBundle:BackendTicket/Grid:edit.html.twig
            form:
                type: Bundle\TicketBundle\Form\Type\TicketType
            repository:
                service: tianos.repository.ticket
                method: find
                arguments: [$ticketId]
                vars:
                    serialize_group_name: crud

backend_ticket_add_client:
    path: /add-cliente
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.ticket:addClienteAction
        _tianos:
            action: create
            template: TicketBundle:BackendTicket/Modal/Client:data.html.twig
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            entity: Bundle\TicketBundle\Entity\Client
            form:
                type: Bundle\TicketBundle\Form\Type\ClientType
            repository:
                vars:
                    serialize_group_name: crud

backend_ticket_add_employee:
    path: /add-employee
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.ticket:addEmployeeAction
        _tianos:
            action: create
            template: TicketBundle:BackendTicket/Modal/Employee:data.html.twig
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            entity: Bundle\TicketBundle\Entity\Employee
            form:
                type: Bundle\TicketBundle\Form\Type\EmployeeType
            repository:
                vars:
                    serialize_group_name: crud

backend_ticket_increment_item:
    path: /increment-item
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.ticket:incrementDecrementItemAction
        _tianos:
            action: create
            template: TicketBundle:BackendTicket/Grid/Box:table_service.html.twig
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            tree:
                icon: file-text-o
                box_class: primary
                title: Gestionar servicios
                main_div: box-main-div
                main_ul: box-main-ul
                child_ul: box-child-ul
                li_span: li-span
            entity: Bundle\TicketBundle\Entity\Services
            form:
                type: Bundle\TicketBundle\Form\Type\ServicesType
            repository:
                vars:
                    serialize_group_name: crud

backend_ticket_decrement_item:
    path: /decrement-item
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.ticket:incrementDecrementItemAction
        _tianos:
            action: create
            template: TicketBundle:BackendTicket/Grid/Box:table_service.html.twig
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            tree:
                icon: file-text-o
                box_class: primary
                title: Gestionar servicios
                main_div: box-main-div
                main_ul: box-main-ul
                child_ul: box-child-ul
                li_span: li-span
            entity: Bundle\TicketBundle\Entity\Services
            form:
                type: Bundle\TicketBundle\Form\Type\ServicesType
            repository:
                vars:
                    serialize_group_name: crud

backend_ticket_remove_all_item:
    path: /remove-all-item
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.ticket:removeAllItemAction
        _tianos:
            action: create
            template: TicketBundle:BackendTicket/Grid/Box:table_service.html.twig
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            entity: Bundle\TicketBundle\Entity\Services
            form:
                type: Bundle\TicketBundle\Form\Type\ServicesType
            repository:
                vars:
                    serialize_group_name: crud

backend_ticket_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.ticket:viewAction
        _tianos:
            action: view
            template: TicketBundle:BackendTicket/Informative:view.html.twig
            repository:
                service: tianos.repository.ticket
                method: find
                arguments: [$ticketId]
                vars:
                    serialize_group_name: crud

backend_ticket_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.ticket:infoAction
        _tianos:
            action: info
            template: TicketBundle:BackendTicket/Informative:info.html.twig
