backend_paymenttype_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.payment.type:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            roles_allow:
                - ROLE_PROFILE_VIEW
            vars:
                subheader: sylius.ui.manage_your_role_catalog
                icon: cube
                body_css: grid-body-css
            grid:
                icon: money
                box_class: primary
                title: Gestionar tipos de pago
                modal:
                    create:
                        title: Crear tipo de pago
                        size: modal-
                    edit:
                        title: Editar tipo de pago
                        size: modal-
                data_table:
                    route:
                        info: backend_paymenttype_info
                        view: backend_paymenttype_view
                        edit: backend_paymenttype_edit
                        create: backend_paymenttype_create
                        delete: backend_paymenttype_delete
                    table_button:
                        #- edit
                        #- delete
                    table_button_header:
                        - create
                        - info
                    table_option:
                        pageLength: 20
                        dom: "'<\"top\"iflp><\"clear\">rt<\"bottom\"iflp>'"
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - obj: " '<span class=\"badge bg-light-blue-active\">' + obj.id + '</span>' "
                          defs:
                              targets: 0
                              searchable: 1
                              sorting: 1
                              orderable: 1
                              type: html
                              width: 4%
                              title: '#'
                              className: modal-view text-center
                        - obj: obj.name
                          defs:
                              targets: 1
                              orderable: 1
                              sorting: 1
                              title: Nombre
                              className: modal-edit
                              filter: 1
                        - obj: " '<span class=\"badge bg-green\">' + obj.slug + '</span>' "
                          defs:
                              targets: 2
                              orderable: 1
                              sorting: 1
                              title: Slug
                              className: text-left
                              filter: 1
                        - obj: obj.created_at
                          defs:
                              targets: 3
                              title: '<i class="fa fa-fw fa-calendar"></i> Creado'
                              className: text-center
                        - obj: " '<button class=\"btn btn-xs btn-danger\"><i class=\"fa fa-fw fa-trash\"></i></button>' "
                          defs:
                              targets: 4
                              title: Eliminar
                              width: 4%
                              sorting: 0
                              orderable: 0
                              className: modal-delete text-center
            form:
                type: Bundle\TicketBundle\Form\Type\PaymentType
            repository:
                service: tianos.repository.payment.type
                method: findAll
                arguments: [$roleId]
                vars:
                    serialize_group_name: crud

backend_paymenttype_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.payment.type:createAction
        _tianos:
            action: create
            template: TicketBundle:PaymentType/Form:form.html.twig
            entity: Bundle\TicketBundle\Entity\PaymentType
            form:
                type: Bundle\TicketBundle\Form\Type\PaymentType
            repository:
                vars:
                    serialize_group_name: crud

backend_paymenttype_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.payment.type:editAction
        _tianos:
            action: edit
            template: TicketBundle:PaymentType/Form:form.html.twig
            form:
                type: Bundle\TicketBundle\Form\Type\PaymentType
            repository:
                service: tianos.repository.payment.type
                method: find
                arguments: [$roleId]
                vars:
                    serialize_group_name: crud

backend_paymenttype_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.payment.type:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            repository:
                service: tianos.repository.payment.type
                method: find
                arguments: [$roleId]
            vars:
#                body_css: grid-body-css

backend_paymenttype_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.payment.type:viewAction
        _tianos:
            action: view
            template: TicketBundle:PaymentType/Informative:view.html.twig
            repository:
                service: tianos.repository.payment.type
                method: find
                arguments: [$roleId]
                vars:
                    serialize_group_name: crud

backend_paymenttype_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.payment.type:infoAction
        _tianos:
            action: info
            template: TicketBundle:PaymentType/Informative:info.html.twig