backend_payment_history_index:
    path: /
    methods: [GET, POST]
    defaults:
        _controller: tianos.backend.controller.payment.history:indexAction
        _tianos:
            action: payment-history
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            tree:
                icon: file-text-o
                box_class: primary
                title: Gestionar xxx
                main_div: box-main-div
                main_ul: box-main-ul
                child_ul: box-child-ul
                li_span: li-span
            entity: Bundle\TicketBundle\Entity\PaymentHistory
            template: TicketBundle:Sales/Modal/PaymentHistory:index.html.twig
            form:
                type: Bundle\TicketBundle\Form\Type\PaymentHistoryType
            repository:
                service: tianos.repository.payment.history
                method: findAllBySales
                arguments: [$ticketId]
                vars:
                    serialize_group_name: sales
