backend_sales_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.sales:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            roles_allow:
                - ROLE_TICKET_VIEW
            vars:
                subheader: sylius.ui.manage_your_ticket_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
            grid:
                icon: shopping-cart
                box_class: primary
                title: Gestionar ventas
                modal:
                    create:
                        title: Crear usuario
                        size: modal-lg
                    edit:
                        title: Editar usuario
                        size: modal-lg
                    view:
                        title: Ver usuario
                        size: modal-lg
                    payment_history:
                        title: Historial de pagos
                        size: modal-lg
                    change_password:
                        title: Cambiar password
                data_table:
                    route:
                        info: backend_sales_info
                        view: backend_sales_view
                        create: backend_sales_create
                        sales_edit: backend_sales_edit
                        payment_history: backend_payment_history_index
                        #delete: backend_sales_delete
                    table_button:
                        #- ticket_edit
                        #- edit
                        #- delete
                    table_button_header:
                        #- create
                        - info
                    table_option:
                        pageLength: 10
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - obj: " '<span class=\"badge bg-light-blue-active\">' + obj.id + '</span>' "
                          defs:
                              targets: 0
                              searchable: 1
                              sorting: 1
                              orderable: 1
                              type: html
                              width: 4%
                              title: '#'
                              className: modal-view text-center
                        - obj: " '<span class=\"label bg-purple fontsize-12\">' + obj.code + '</span>' "
                          defs:
                              targets: 1
                              searchable: 1
                              sorting: 1
                              orderable: 1
                              type: html
                              width: 12%
                              title: '<i class="fa fa-fw fa-qrcode"></i> Code'
                              className: modal-payment-history text-center
                              filter: 1
                        - obj: obj.status
                          options:
                              property: " if(obj.status == 1){return '<span class=\"label label-success fontsize-12\">ABIERTO</span>'}else if(obj.status == 3){return '<span class=\"label label-danger fontsize-12\">CERRADO</span>'} "
                          defs:
                              targets: 2
                              orderable: 1
                              sorting: 1
                              title: Status
                              width: 10%
                              className: text-center
                              filter: 0
                        - obj: obj.client.name_box
                          defs:
                              targets: 3
                              orderable: 1
                              sorting: 1
                              title: '<i class="fa fa-fw fa-user"></i> Cliente'
                              className: text-center
                              filter: 1
                        - obj: obj.point_of_sale
                          options:
                              property: " return (obj.point_of_sale) ? obj.point_of_sale.name : '' "
                          defs:
                              targets: 4
                              orderable: 1
                              sorting: 1
                              title: '<i class="fa fa-fw fa-map-marker"></i> Punto de venta'
                              className: text-center
                              filter: 1
                        - obj: obj.total
                          defs:
                              targets: 5
                              orderable: 1
                              sorting: 1
                              title: '<i class="fa fa-fw fa-money"></i> Total'
                              className: text-center
                              filter: 1
                        - obj: obj.delivery_date
                          defs:
                              targets: 6
                              title: '<i class="fa fa-fw fa-calendar"></i> Fecha de entrega'
                              className: text-center
                        - obj: obj.created_at
                          defs:
                              targets: 7
                              title: '<i class="fa fa-fw fa-calendar"></i> Creado'
                              className: text-center
            form:
                type: Bundle\TicketBundle\Form\Type\SalesType
            repository:
                service: tianos.repository.sales
                method: findAll
                arguments: [$ticketId]
                vars:
                    serialize_group_name: sales

backend_sales_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: tianos.backend.controller.sales:createAction
        _tianos:
            action: create
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            tree:
                icon: file-text-o
                box_class: primary
                title: Gestionar xxx
                main_div: box-main-div
                main_ul: box-main-ul
                child_ul: box-child-ul
                li_span: li-span
            entity: Bundle\TicketBundle\Entity\Sales
            template: TicketBundle:Sales/Grid:create.html.twig
            form:
                type: Bundle\TicketBundle\Form\Type\SalesType
            repository:
                vars:
                    serialize_group_name: sales

backend_sales_edit:
    path: /edit/{id}
    methods: [GET, POST]
    defaults:
        id: null
        _controller: tianos.backend.controller.ticket:editAction
        _tianos:
            action: edit
            vars:
               body_css: grid-body-css
               serialize_group_name: crud
            tree:
               icon: file-text-o
               box_class: primary
               title: Gestionar servicios
               main_div: box-main-div
               main_ul: box-main-ul
               child_ul: box-child-ul
               li_span: li-span
            entity: Bundle\TicketBundle\Entity\Ticket
            template: TicketBundle:BackendTicket/Grid:edit.html.twig
            form:
                type: Bundle\TicketBundle\Form\Type\TicketType
            repository:
                service: tianos.repository.sales
                method: find
                arguments: [$ticketId]
                vars:
                    serialize_group_name: sales

backend_sales_add_client:
    path: /add-cliente
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.sales:addClienteAction
        _tianos:
            action: create
            template: TicketBundle:Sales/Modal/Client:data.html.twig
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            entity: Bundle\TicketBundle\Entity\Client
            form:
                type: Bundle\TicketBundle\Form\Type\ClientType
            repository:
                service: tianos.repository.user
                method: findAllClient
                vars:
                    serialize_group_name: sales

backend_sales_increment_item:
    path: /increment-item
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.sales:incrementDecrementItemAction
        _tianos:
            action: create
            template: TicketBundle:Sales/Grid/Box:table_product.html.twig
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            tree:
                icon: file-text-o
                box_class: primary
                title: Gestionar product
                main_div: box-main-div
                main_ul: box-main-ul
                child_ul: box-child-ul
                li_span: li-span
            entity: Bundle\ProductBundle\Entity\Product
            form:
                type: Bundle\ProductBundle\Form\Type\ProductType
            repository:
                vars:
                    serialize_group_name: sales

backend_sales_decrement_item:
    path: /decrement-item
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.sales:incrementDecrementItemAction
        _tianos:
            action: create
            template: TicketBundle:Sales/Grid/Box:table_product.html.twig
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            tree:
                icon: file-text-o
                box_class: primary
                title: Gestionar servicios
                main_div: box-main-div
                main_ul: box-main-ul
                child_ul: box-child-ul
                li_span: li-span
            entity: Bundle\ProductBundle\Entity\Product
            form:
                type: Bundle\ProductBundle\Form\Type\ProductType
            repository:
                vars:
                    serialize_group_name: sales

backend_sales_remove_all_item:
    path: /remove-all-item
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.ticket:removeAllItemAction
        _tianos:
            action: create
            template: TicketBundle:BackendTicket/Grid/Box:table_product.html.twig
            vars:
                body_css: grid-body-css
                serialize_group_name: crud
            entity: Bundle\TicketBundle\Entity\Services
            form:
                type: Bundle\TicketBundle\Form\Type\ServicesType
            repository:
                vars:
                    serialize_group_name: sales

backend_sales_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.sales:viewAction
        _tianos:
            action: view
            template: TicketBundle:Sales/Informative:view.html.twig
            repository:
                service: tianos.repository.sales
                method: find
                arguments: [$ticketId]
                vars:
                    serialize_group_name: sales

backend_sales_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.ticket:infoAction
        _tianos:
            action: info
            template: TicketBundle:BackendTicket/Informative:info.html.twig
