backend_default:
    resource: '@BackendBundle/Resources/config/routing/default_pdv.yml'
    prefix: /
backend_security_pdv:
    resource: '@UserBundle/Resources/config/routing/security_pdv.yml'
    prefix: /login
backend_session:
    resource: '@SessionBundle/Resources/config/routing/backend.yml'
    prefix: /session
backend_report:
    resource: '@ReportBundle/Resources/config/routing/backend.yml'
    prefix: /report
backend_user_client:
    resource: '@UserBundle/Resources/config/routing/backend_client.yml'
    prefix: /user-client
backend_user_employee:
    resource: '@UserBundle/Resources/config/routing/backend_employee.yml'
    prefix: /user-employee
backend_services:
    resource: '@ServicesBundle/Resources/config/routing/backend.yml'
    prefix: /services
backend_user:
    resource: '@UserBundle/Resources/config/routing/backend_pdv.yml'
    prefix: /user
backend_report:
    resource: '@ReportBundle/Resources/config/routing/backend.yml'
    prefix: /report

backend_category:
    resource: '@CategoryBundle/Resources/config/routing/tree.yml'
    prefix: /category
backend_product:
    resource: '@ProductBundle/Resources/config/routing/backend.yml'
    prefix: /product

backend_ticket:
    resource: '@TicketBundle/Resources/config/routing/backend.yml'
    prefix: /ticket

backend_pointofsale:
    resource: '@PointofsaleBundle/Resources/config/routing/backend.yml'
    prefix: /point-of-sale
backend_pointofsale_map:
    resource: '@PointofsaleBundle/Resources/config/routing/backend_map.yml'
    prefix: /point-of-sale/map
backend_pointofsale_per_user:
    resource: '@PointofsaleBundle/Resources/config/routing/backend_per_user.yml'
    prefix: /point-of-sale-per-user