backend_super_default:
    resource: '@BackendBundle/Resources/config/routing/default_super.yml'
    prefix: /
backend_super_role:
    resource: '@RoleBundle/Resources/config/routing/backend.yml'
    prefix: /role
backend_super_profile:
    resource: '@ProfileBundle/Resources/config/routing/backend.yml'
    prefix: /profile
backend_security_super:
    resource: '@UserBundle/Resources/config/routing/security_super.yml'
    prefix: /security
backend_super_session:
    resource: '@SessionBundle/Resources/config/routing/backend.yml'
    prefix: /session
backend_super_pointofsale:
    resource: '@PointofsaleBundle/Resources/config/routing/backend.yml'
    prefix: /point-of-sale
backend_super_user:
    resource: '@UserBundle/Resources/config/routing/backend_super.yml'
    prefix: /user
backend_super_pointofsale_pdv_child:
    resource: '@PointofsaleBundle/Resources/config/routing/backend_super_pdv_child.yml'
    prefix: /point-of-sale-child
backend_super_pointofsale_add_user:
    resource: '@PointofsaleBundle/Resources/config/routing/backend_super_add_user.yml'
    prefix: /point-of-sale-add-user
backend_super_pointofsale_map:
    resource: '@PointofsaleBundle/Resources/config/routing/backend_super_map.yml'
    prefix: /point-of-sale/map
backend_super_files:
    resource: '@FilesBundle/Resources/config/routing/backend.yml'
    prefix: /files
