services:

    sylius.form.type.admin_user:
        class: Bundle\UserBundle\Form\Type\UserType
        arguments: [ "%sylius.model.admin_user.class%" ]
        tags:
            - { name: sylius.form.type.admin_user, alias: sylius.form.type.admin_user }

    Bundle\CoreBundle\DataFixtures\ORM\Load_1_PointofsaleData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_2_RoleData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_3_ProfileData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_4_UserData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_5_CategoryData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_12_UserHasPointOfSaleData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_14_PointofsaleBranchOfficeData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_15_PointofsaleHasUserData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_16_ServicesData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_17_UnitData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_18_ColorData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_19_ProductoData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_20_PaymentTypeData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_21_PdvHasProductData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    Bundle\CoreBundle\DataFixtures\ORM\Load_22_SettingsData:
        arguments: [ '%application_url%' ]
        tags: [doctrine.fixture.orm]

    tianos.core.controller.default:
        class: Bundle\CoreBundle\Controller\DefaultController
        tags:
            - { name: tianos.core.controller.default, alias: tianos.core.controller.default }

    twig.extension.common:
         class: Bundle\CoreBundle\Twig\Extension\CommonExtension
         public: false
         tags:
             - { name: twig.extension }
