Bundle\TicketBundle\Entity\SalesHasProducts:
    type: entity
    table: sales_has_products
    repositoryClass: Bundle\TicketBundle\Doctrine\ORM\SalesHasProductsRepository
    indexes:
        fk_sales_has_products_sales1_idx:
            columns:
                - sales_id
        fk_sales_has_products_product1_idx:
            columns:
                - product_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: float
            nullable: false
            options:
                unsigned: false
            column: quantity
        unitPrice:
            type: float
            nullable: true
            precision: 8
            scale: 2
            options:
                fixed: false
            column: unit_price
    manyToOne:
        product:
            targetEntity: Bundle\ProductBundle\Entity\Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
        sales:
            targetEntity: Bundle\TicketBundle\Entity\Sales
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sales_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
