backend_super_product_index:
    path: /{categoryId}
    methods: [GET]
    defaults:
        categoryId: null
        _controller: tianos.backend.controller.product:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index_inventory_super.html.twig
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube
                body_css: grid-body-css
                serialize_group_name: crud
#            grid: sylius_admin_product
            tree:
                icon: dropbox
                box_class: primary
                title: Gestionar servicios
                main_div: box-main-div
                main_ul: box-main-ul
                child_ul: box-child-ul
                li_span: li-span
                route:
                    info: backend_super_category_tree_info
                    view: backend_super_category_tree_view
                    edit: backend_super_category_tree_edit
                    create: backend_super_category_tree_create
                    create_child: backend_super_category_tree_create_child
                    delete: backend_super_category_tree_delete
            grid:
                icon: dropbox
                box_class: primary
                title: Gestionar inventario
                modal:
                    create:
                        title: Crear producto
                        size: modal-
                    edit:
                        title: Editar producto
                        size: modal-
                data_table:
                    route:
                        info: backend_super_product_info
                        view: backend_super_product_view
                        edit: backend_super_product_edit
                        create: backend_super_product_create
                        delete: backend_super_product_delete
                    table_button:
                        - edit
                        - delete
                    table_button_header:
#                        - create
                        - info
                    table_option:
                        pageLength: 10
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - name: '#'
                          obj: " '<span class=\"badge bg-blue\">' + obj.id + '</span>' "
                        - name: Name
                          obj: obj.name
                        - name: Stock
                          obj: obj.stock
#                        - name: Creado
#                          obj: obj.created_at
#                          options:
#                              icon: calendar
            form:
                type: Bundle\ProductBundle\Form\Type\ProductType
            repository:
                service: tianos.repository.product
                method: findAllByCategory
                arguments: [$productId]
                vars:
                    serialize_group_name: crud
                    entity_type: product

backend_super_product_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.product:createAction
        _tianos:
            action: create
            template: ProductBundle:BackendProduct/Form:form.html.twig
            entity: Bundle\ProductBundle\Entity\Product
            form:
                type: Bundle\ProductBundle\Form\Type\ProductType
            repository:
                vars:
                    serialize_group_name: crud

backend_super_product_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.product:editAction
        _tianos:
            action: edit
            template: ProductBundle:BackendProduct/Form:form.html.twig
            form:
                type: Bundle\ProductBundle\Form\Type\ProductType
            repository:
                service: tianos.repository.product
                method: find
                arguments: [$productId]
                vars:
                    serialize_group_name: crud

backend_super_product_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.product:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            repository:
                service: tianos.repository.product
                method: find
                arguments: [$productId]
            vars:
#                body_css: grid-body-css

backend_super_product_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.product:viewAction
        _tianos:
            action: view
            template: ProductBundle:BackendProduct/Informative:view.html.twig
            repository:
                service: tianos.repository.product
                method: find
                arguments: [$productId]
                vars:
                    serialize_group_name: crud

backend_super_product_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.product:infoAction
        _tianos:
            action: info
            template: ProductBundle:BackendProduct/Informative:info.html.twig

