backend_color_index:
    path: /
    methods: [GET]
    defaults:
        _controller: tianos.backend.controller.color:indexAction
        _tianos:
            action: index
            section: admin
            permission: true
            template: GridBundle::index.html.twig
            roles_granted:
                - ROLE_PRODUCT_VIEW
            vars:
                subheader: sylius.ui.manage_your_profile_catalog
                icon: cube
                body_css: grid-body-css
            grid:
                icon: adjust
                box_class: primary
                title: Gestionar color
                modal:
                    create:
                        title: Crear color
                        size: modal-
                    edit:
                        size: modal-
                data_table:
                    route:
                        info: backend_color_info
                        view: backend_color_view
                        edit: backend_color_edit
                        create: backend_color_create
                        delete: backend_color_delete
                    table_button:
                        #- edit
                        #- delete
                    table_button_header:
                        - create
                        - info
                    table_option:
                        pageLength: 50
                        dom: "'<\"top\"iflp><\"clear\">rt<\"bottom\"iflp>'"
                    row_call_back:
                        - key: id
                          value: aData.id
                        - key: data-id
                          value: aData.id
                        - key: class
                          value: "'alert'"
                    columns:
                        - obj: " '<span class=\"badge bg-light-blue-active\">' + obj.id + '</span>' "
                          defs:
                              targets: 0
                              searchable: 1
                              sorting: 1
                              orderable: 1
                              type: html
                              width: 4%
                              title: '#'
                              className: modal-view text-center
                        - obj: " '<div class=\"alert product-color\" style=\"background-color:' + obj.prefix + '\"></div>' "
                          defs:
                              targets: 1
                              orderable: 1
                              sorting: 1
                              width: 8%
                              title: '<i class="fa fa-fw fa-adjust"></i> Prefijo'
                              className: padding-0 text-center
                              filter: 0
                        - obj: obj.name
                          defs:
                              targets: 2
                              orderable: 1
                              sorting: 1
                              title: Nombre
                              className: modal-edit
                              filter: 1
                        - obj: obj.created_at
                          defs:
                              targets: 3
                              title: '<i class="fa fa-fw fa-calendar"></i> Creado'
                              className: text-center
            form:
                type: Bundle\ProductBundle\Form\Type\ColorFormType
            repository:
                service: tianos.repository.color
                method: findAll
                arguments: [$profileId]
                vars:
                    serialize_group_name: crud

backend_color_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.color:createAction
        _tianos:
            action: create
            template: ProductBundle:Color/Form:form.html.twig
            entity: Bundle\ProductBundle\Entity\Color
            roles_granted:
                - ROLE_PRODUCT_CREATE
            form:
                type: Bundle\ProductBundle\Form\Type\ColorFormType
            repository:
                vars:
                    serialize_group_name: crud

backend_color_edit:
    path: /edit
    methods: [PUT, POST]
    defaults:
        _controller: tianos.backend.controller.color:editAction
        _tianos:
            action: edit
            template: ProductBundle:Color/Form:form.html.twig
            roles_granted:
                - ROLE_PRODUCT_EDIT
            form:
                type: Bundle\ProductBundle\Form\Type\ColorFormType
            repository:
                service: tianos.repository.color
                method: find
                arguments: [$profileId]
                vars:
                    serialize_group_name: crud

backend_color_delete:
    path: /delete
    methods: [POST, DELETE]
    defaults:
        _controller: tianos.backend.controller.color:deleteAction
        _tianos:
            action: delete
            template: GridBundle:Template:delete.html.twig
            roles_granted:
                - ROLE_PRODUCT_DELETE
            repository:
                service: tianos.repository.color
                method: find
                arguments: [$profileId]
            vars:
#                body_css: grid-body-css

backend_color_view:
    path: /view
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.color:viewAction
        _tianos:
            action: view
            template: ProductBundle:Color/Informative:view.html.twig
            roles_granted:
                - ROLE_PRODUCT_VIEW
            repository:
                service: tianos.repository.color
                method: find
                arguments: [$profileId]
                vars:
                    serialize_group_name: crud

backend_color_info:
    path: /info
    methods: [POST]
    defaults:
        _controller: tianos.backend.controller.color:infoAction
        _tianos:
            action: info
            template: ProductBundle:Color/Informative:info.html.twig